#! /usr/bin/env bash

bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor HDMI-A-1 -d 1 2 3 4 5
bspc monitor HDMI-A-2 -d 1 2 3 4 5

bspc config border_width		4
bspc config window_gap			10
bspc config split_ratio 		0.5
bspc config single_monocle		false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config gapless_monocle		true

bspc config focused_border_color	"#BD93F9"
bspc config normal_border_color		"#282A36"
bspc config active_border_color		"#8BE9FD"
bspc config presel_feedback_color	"#50FA7B"

sxhkd &
picom --config ~/.config/picom/picom.conf &
dunst &
polybar &
kitty &
feh --bg-scale -z -r ~/img/bg.png &

xsetroot -cursor_name left-ptr
xset r rate 200 50
